# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/lcsk42"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://x.com/lcsk42"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "mail"
name = "Mail"
url = "mailto:lcsk42@gmail.com"

[social.params]
icon = "brand-mail"

[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"

[social.params]
icon = "brand-rss"
